name: Releases

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: [self-hosted, linux, dtlqc]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-05-20
          components: rust-src, llvm-tools, clippy, rustfmt
          targets: >
            x86_64-unknown-none,
            riscv64gc-unknown-none-elf,
            aarch64-unknown-none-softfloat,
            loongarch64-unknown-none-softfloat
      - run: cargo install cargo-binutils
      - name: Build for all platforms
        run: |
          set -e
          ./build.sh qemu-x86_64
          ./build.sh qemu-riscv64
          ./build.sh qemu-aarch64
          ./build.sh phytiumpi
          ./build.sh tac-e400-plc
        
      - name: Prepare release files
        id: release
        run: ./build.sh release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ steps.release.outputs.RELEASE_DIR }}/*
          body: |
            ## 客户机镜像文件
            
            本次发布包含以下平台的构建产物:
            - QEMU (x86_64, RISC-V, AArch64, LoongArch)
            - 飞腾派 (Phytium Pi)
            - ROC-RK3568-PC 开发板
            - TAC-E400-PLC 工业计算机
            
            文件命名格式: `arceos-{board}-{arch}-{config}.bin`
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true